import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom'
import { AuthProvider } from './AuthContext'
import { ToastProvider } from './useToast'
import AppLayout from './AppLayout'
import ProtectedRoute from './ProtectedRoute'
import Home from './Home'
import Auth from './Auth'
import Create from './Create'
import CreateStory from './CreateStory'
import Profile from './Profile'
import UserProfile from './UserProfile'
import Settings from './Settings'
import Messages from './Messages'
import Notifications from './Notifications'
import Explore from './Explore'
import Reels from './Reels'
